// Copyright IBM Corp. 2016, 2025
// SPDX-License-Identifier: MPL-2.0

package provider

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/ephemeral"
	"github.com/hashicorp/terraform-plugin-framework/ephemeral/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-random/internal/diagnostics"
)

var (
	_ ephemeral.EphemeralResource = (*bytesEphemeralResource)(nil)
)

func NewBytesEphemeralResource() ephemeral.EphemeralResource {
	return &bytesEphemeralResource{}
}

type bytesEphemeralResource struct{}

type ephemeralBytesModel struct {
	Length types.Int64  `tfsdk:"length"`
	Base64 types.String `tfsdk:"base64"`
	Hex    types.String `tfsdk:"hex"`
}

func (e *bytesEphemeralResource) Metadata(ctx context.Context, req ephemeral.MetadataRequest, resp *ephemeral.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_bytes"
}

func (e *bytesEphemeralResource) Schema(ctx context.Context, req ephemeral.SchemaRequest, resp *ephemeral.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "-> If the managed resource doesn't have a write-only argument available for the secret (first introduced in Terraform 1.11), then the " +
			"secret can only be created with the managed resource variant of [`random_bytes`](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/bytes).\n" +
			"\n" +
			"Generates ephemeral random bytes using a cryptographic random number generator.\n" +
			"\n" +
			"The primary use-case for generating ephemeral random bytes is to be used in combination with a write-only argument " +
			"in a managed resource, which will avoid Terraform storing the secret value in the plan or state file.",
		Attributes: map[string]schema.Attribute{
			"length": schema.Int64Attribute{
				Description: "The number of bytes requested. The minimum value for length is 1.",
				Required:    true,
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
			},
			"base64": schema.StringAttribute{
				Description: "The generated bytes presented in base64 string format.",
				Computed:    true,
				Sensitive:   true,
			},
			"hex": schema.StringAttribute{
				Description: "The generated bytes presented in lowercase hexadecimal string format. " +
					"The length of the encoded string is exactly twice the `length` parameter.",
				Computed:  true,
				Sensitive: true,
			},
		},
	}
}

func (e *bytesEphemeralResource) Open(ctx context.Context, req ephemeral.OpenRequest, resp *ephemeral.OpenResponse) {
	var data ephemeralBytesModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	bytes := make([]byte, data.Length.ValueInt64())
	_, err := rand.Read(bytes)
	if err != nil {
		resp.Diagnostics.Append(diagnostics.RandomReadError(err.Error())...)
		return
	}

	data.Base64 = types.StringValue(base64.StdEncoding.EncodeToString(bytes))
	data.Hex = types.StringValue(hex.EncodeToString(bytes))

	resp.Diagnostics.Append(resp.Result.Set(ctx, data)...)
}
